# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hunt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='server.Hunt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='hunt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='server.Hunt'),
            preserve_default=False,
        ),
    ]
