# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 01:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170923_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hunt',
            name='private_token',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='hunt',
            name='public_token',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
