# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20170923_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='server.Item'),
            preserve_default=False,
        ),
    ]
