# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_transaction_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
