# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_hunt_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.PositiveIntegerField(),
        ),
    ]
