# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 01:41
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0006_auto_20170927_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HuntAuthorizationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(8)])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hunt',
            name='public_token',
        ),
        migrations.AlterField(
            model_name='item',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hunt'),
        ),
        migrations.AlterField(
            model_name='item',
            name='points',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Region'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hunt'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Player'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.Region'),
        ),
        migrations.AddField(
            model_name='huntauthorizationtoken',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hunt'),
        ),
        migrations.AddField(
            model_name='authorizedusers',
            name='hunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.Hunt'),
        ),
        migrations.AddField(
            model_name='authorizedusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
