# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-22 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20170930_0136'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('uuid', 'name')]),
        ),
    ]
